apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-panel
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admin-panel
  template:
    metadata:
      labels:
        app: admin-panel
    spec:
      containers:
      - name: admin-panel
        image: delvinjoseph07/capstone-admin:latest  # <--- Change to your Docker Hub username
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: admin-panel
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: admin-panel